package_path: assets
gzip_assets: off
compress_assets: off

javascripts:
  libs:
    - public/javascripts/jquery-1.6.2.js
    - public/javascripts/jquery.layout-1.3.0.js
    - public/javascripts/jquery.timers.js
    - public/javascripts/jquery.autocomplete.js
    - public/javascripts/json2.js
    - public/javascripts/patches.js
    - public/javascripts/keymaster.js
    - public/javascripts/underscore.js
    - public/javascripts/backbone.js
    - public/javascripts/stacktrace.js
  application:
    - build/javascripts/application.js
    - build/javascripts/*_util.js
    - build/javascripts/models/*.js
    - build/javascripts/views/**/*.js
    - build/javascripts/controllers/*.js
    - views/javascripts/views/**/*.jst
    - build/javascripts/sb.js

stylesheets:
  all:
    - build/stylesheets/*.css
